[package]
name = "rsst"
version = "1.0.0"
authors = ["Ty Kozic <tykozic@protonmail.com>"]
edition = "2018"

[profile.release]
opt-level = "s"

[dependencies]
reqwest = { version = "0.11.2", features = ["blocking"] }
xml-rs = "0.8.3"
